export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const PRICE_FILTER = "PRICE_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";